#pragma once
#define PLUGIN_NAME "RG Bremen"
#define PLUGIN_VERSION "1.2.2"
#define PLUGIN_DEVELOPER "Sebastian Kramer"
#define PLUGIN_COPYRIGHT "Free To Distribute"

#define RG_BREMEN_TAG_ITEM_VFR_INDICATOR 1
#define RG_BREMEN_TAG_ITEM_VFR_CALLSIGN 2
#define RG_BREMEN_TAG_ITEM_GROUNDSPEED 3
#define RG_BREMEN_TAG_ITEM_ALTITUDE 4
#define RG_BREMEN_TAG_ITEM_VS_INDICATOR 5
#define RG_BREMEN_TAG_ITEM_VS_SPEED 6
#define RG_BREMEN_TAG_ITEM_IAS 7
#define RG_BREMEN_TAG_ITEM_DESTINATION 8
#define RG_BREMEN_TAG_ITEM_SIDSTAR 10
#define RG_BREMEN_TAG_ITEM_CFL 11
#define RG_BREMEN_TAG_ITEM_AHDG 13
#define RG_BREMEN_TAG_ITEM_NORDO 14
#define RG_BREMEN_TAG_ITEM_TWR_CALLSIGN 17
#define RG_BREMEN_TAG_ITEM_COPX 18
#define RG_BREMEN_TAG_ITEM_XFL 19
#define RG_BREMEN_TAG_ITEM_NEXTSECTOR 20

#define RG_BREMEN_LIST_ITEM_CLBSID 9
#define RG_BREMEN_LIST_ITEM_DESCSTAR 12

#define RG_BREMEN_TAG_ITEM_FUNC_NORDO_SET 15
#define RG_BREMEN_TAG_ITEM_FUNC_NORDO_CLEAR 16

#define RG_BREMEN_TAG_COLOR_ASSUMED RGB(253, 167, 78)
#define RG_BREMEN_TAG_COLOR_CONCERNED RGB(255,255,255)
#define RG_BREMEN_TAG_COLOR_UNCONCERNED RGB(112,134,179)
#define RG_BREMEN_TAG_COLOR_VFR RGB(103,151,121)
#define RG_BREMEN_TAG_COLOR_TWR RGB(270,170,15)
#define RG_BREMEN_TAG_COLOR_HANDOFF RGB(255,255,255)

// IS NOW DEFINED IN CONFIG
//#define RG_BREMEN_CLIMB_SID_FILE_URL "https://nav.vatsim-germany.org/files/edww/euroscope/public/clbdesc_sidstar.txt"
//#define RG_BREMEN_CLIMB_SID_FILE_URL "https://dms.vatsim-germany.org/s/GgfH7KN72YfCFcM"
//#define RG_BREMEN_CLIMB_SID_FILE_URL "https://dms.vatsim-germany.org/s/CQxss89irorjZmp/download/clbdesc_sidstar.txt"

#define RG_BREMEN_SCENARIO_CREATOR_URL "https://dev.vatsim-germany.org/api/euroscope/scenario"
#define RG_BREMEN_SCENARIO_CREATOR_KEY "aVAKKA8Bi9fiiPiOlJ6KlkTCpW93YKo68GYQb80FEvV1RVMlNU9vRBYt0kBkjkNwv2lETcClHn6FU6IA1pFlLnDLOvFY83YH2jVxURz8bh0sklHwcH4oxeHzZyVtLNHuORbtnSAdyec4ztxkP3Z0clkRNLpJRLVxNIZMYZYNVsn4B9fRbLCxBlG4UXD6fborKHvtu2YTq2n6C2KytzZFFRHaXY6REzDV6vLM5AGdujSVVkMh7XxbQbQ9Uwfl8fLH"