#pragma once

#define PLUGIN_NAME		"RG Bremen EuroScope PlugIn"
#define PLUGIN_VERSION   "2.0.0"
#define PLUGIN_DEVELOPER "Sebastian Kramer"
#define PLUGIN_COPYRIGHT "GPL v3"


#define LIST_ITEM_SID_CHECK 101
#define LIST_ITEM_STAR_CHECK 102

#define TAG_ITEM_GROUNDSPEED 1001
#define TAG_ITEM_ALTITUDE 1002
#define TAG_ITEM_VERTICAL_SPEED_INDICATOR 1003
#define TAG_ITEM_VERTICAL_SPEED 1004
#define TAG_ITEM_INDICATED_AIRSPEED 1005
