#pragma once

#define RG_BREMEN_PLUGIN_NAME		"RG Bremen EuroScope PlugIn"
#define RG_BREMEN_PLUGIN_VERSION   "2.0.0"
#define RG_BREMEN_PLUGIN_DEVELOPER "Sebastian Kramer"
#define RG_BREMEN_PLUGIN_COPYRIGHT "GPL v3"


#define RG_BREMEN_LIST_ITEM_SID_CHECK 101
#define RG_BREMEN_LIST_ITEM_STAR_CHECK 102

#define RG_BREMEN_TAG_ITEM_GROUNDSPEED 1001
#define RG_BREMEN_TAG_ITEM_ALTITUDE 1002
#define RG_BREMEN_TAG_ITEM_VERTICAL_SPEED_INDICATOR 1003
#define RG_BREMEN_TAG_ITEM_VERTICAL_SPEED 1004
#define RG_BREMEN_TAG_ITEM_INDICATED_AIRSPEED 1005
#define RG_BREMEN_TAG_ITEM_DESTINATION 1006
#define RG_BREMEN_TAG_ITEM_SIDSTAR 1007
#define RG_BREMEN_TAG_ITEM_CLEARED_FLIGHT_LEVEL 1008
#define RG_BREMEN_TAG_ITEM_ASSIGNED_HEADING 1009
#define RG_BREMEN_TAG_ITEM_COPX 1010
#define RG_BREMEN_TAG_ITEM_TRANSFER_FLIGHT_LEVEL 1011
#define RG_BREMEN_TAG_ITEM_NEXT_SECTOR 1012

#define RG_BREMEN_TAG_ITEM_VFR_INDICATOR 2001
#define RG_BREMEN_TAG_ITEM_VFR_CALLSIGN 2002
#define RG_BREMEN_TAG_ITEM_VFR_ALTITUDE 2003
#define RG_BREMEN_TAG_ITEM_VFR_INDICATED_AIRSPEED 2004

#define RG_BREMEN_TAG_ITEM_TWR_INDICATOR 3001
#define RG_BREMEN_TAG_ITEM_TWR_CALLSIGN 3002
#define RG_BREMEN_TAG_ITEM_TWR_ALTITUDE 3003
#define RG_BREMEN_TAG_ITEM_TWR_INDICATED_AIRSPEED 3004