#pragma once

#define RG_BREMEN_PLUGIN_NAME		"RG Bremen EuroScope PlugIn"
#define RG_BREMEN_PLUGIN_VERSION   "2.0.0"
#define RG_BREMEN_PLUGIN_DEVELOPER "Sebastian Kramer"
#define RG_BREMEN_PLUGIN_COPYRIGHT "GPL v3"


#define RG_BREMEN_LIST_ITEM_SID_CHECK 101
#define RG_BREMEN_LIST_ITEM_STAR_CHECK 102

#define RG_BREMEN_TAG_ITEM_GROUNDSPEED 1001
#define RG_BREMEN_TAG_ITEM_ALTITUDE 1002
#define RG_BREMEN_TAG_ITEM_VERTICAL_SPEED_INDICATOR 1003
#define RG_BREMEN_TAG_ITEM_VERTICAL_SPEED 1004
#define RG_BREMEN_TAG_ITEM_INDICATED_AIRSPEED 1005
#define RG_BREMEN_TAG_ITEM_DESTINATION 1006
#define RG_BREMEN_TAG_ITEM_SIDSTAR 1007
#define RG_BREMEN_TAG_ITEM_CLEARED_FLIGHT_LEVEL 1008
#define RG_BREMEN_TAG_ITEM_ASSIGNED_HEADING 1009
#define RG_BREMEN_TAG_ITEM_COPX 1010
#define RG_BREMEN_TAG_ITEM_TRANSFER_FLIGHT_LEVEL 1011
#define RG_BREMEN_TAG_ITEM_NEXT_SECTOR 1012

#define RG_BREMEN_TAG_ITEM_VFR_INDICATOR 2001
#define RG_BREMEN_TAG_ITEM_VFR_CALLSIGN 2002
#define RG_BREMEN_TAG_ITEM_VFR_ALTITUDE 2003
#define RG_BREMEN_TAG_ITEM_VFR_INDICATED_AIRSPEED 2004

#define RG_BREMEN_TAG_ITEM_TWR_INDICATOR 3001
#define RG_BREMEN_TAG_ITEM_TWR_CALLSIGN 3002
#define RG_BREMEN_TAG_ITEM_TWR_ALTITUDE 3003
#define RG_BREMEN_TAG_ITEM_TWR_INDICATED_AIRSPEED 3004

#define RG_BREMEN_TAG_ITEM_CALCULATED_IAS 4001
#define RG_BREMEN_TAG_ITEM_CALCULATED_IAS_TOGGLABLE 4002
#define RG_BREMEN_TAG_ITEM_CALCULATED_IAS_ABBREVIATED 4003
#define RG_BREMEN_TAG_ITEM_CALCULATED_IAS_ABBREVIATED_TOGGLABLE 4004
#define RG_BREMEN_TAG_ITEM_CALCULATED_MACH 4005
#define RG_BREMEN_TAG_ITEM_CALCULATED_MACH_TOGGLABLE 4006
#define RG_BREMEN_TAG_ITEM_CALCULATED_MACH_ABOVE_THRESHOLD 4007
#define RG_BREMEN_TAG_ITEM_CALCULATED_MACH_ABOVE_THRESHOLD_TOGGLABLE 4008

#define RG_BREMEN_TAG_ITEM_FUNC_OPEN_REPORTED_IAS_MENU 10001
#define RG_BREMEN_TAG_ITEM_FUNC_CLEAR_REPORTED_IAS 10002
#define RG_BREMEN_TAG_ITEM_FUNC_TOGGLE_CALCULATED_IAS 10003
#define RG_BREMEN_TAG_ITEM_FUNC_TOGGLE_CALCULATED_IAS_ABBREVIATED 10004
#define RG_BREMEN_TAG_ITEM_FUNC_OPEN_REPORTED_MACH_MENU 10005
#define RG_BREMEN_TAG_ITEM_FUNC_CLEAR_REPORTED_MACH 10006
#define RG_BREMEN_TAG_ITEM_FUNC_TOGGLE_CALCULATED_MACH 10007
#define RG_BREMEN_TAG_ITEM_FUNC_TOGGLE_CALCULATED_MACH_ABOVE_THRESHOLD 10008
#define RG_BREMEN_TAG_ITEM_FUNC_TOGGLE_UNRELIABLE_SPEED 10009
#define RG_BREMEN_TAG_ITEM_FUNC_SET_REPORTED_IAS 10010
#define RG_BREMEN_TAG_ITEM_FUNC_SET_REPORTED_MACH 10011

constexpr auto SETTINGS_DELIMITER = '|';
constexpr auto BROADCAST_DELIMITER = '/';
constexpr auto BROADCAST_PREFIX = "IAS";
constexpr auto BROADCAST_UNRELIABLE_SPEED = "US";
const int BROADCAST_FLIGHT_STRIP_INDEX = 4;

const int MIN_REPORTED_IAS = 100;
const int MAX_REPORTED_IAS = 600;
const int INTERVAL_REPORTED_IAS = 5;
const int MIN_REPORTED_MACH = 01;
const int MAX_REPORTED_MACH = 99;
const int INTERVAL_REPORTED_MACH = 1;
const int MIN_MACH_DIGITS = 1;
const int MAX_MACH_DIGITS = 5;
const int TAG_ITEM_MAX_CONTENT_LENGTH = 14;